version: '3'
services:
  composer:
    image: composer:latest
    environment:
      - COMPOSER_CACHE_DIR=/app/storage/cache/composer
    volumes:
      - .:/app
    restart: never
    #provision php cli
  php:
    image: php:7.4-cli    
    volumes:
      - .:/app
    working_dir: /app
    restart: never
  test:
    image: php:7.4-cli
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit